name: Deploy to Cloud Run

on:
  push:
    branches: [main]

env:
  PROJECT_ID: huashui-ai-450006
  REGION: asia-east1
  SERVICE: image-processor

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: 'beta'

      - name: 'Configure Docker'
        run: gcloud auth configure-docker asia-east1-docker.pkg.dev

      - name: 'Build and Deploy'
        run: |
          gcloud builds submit --tag gcr.io/$PROJECT_ID/$SERVICE \
            --timeout=1800s \
            --quiet
          gcloud run deploy $SERVICE \
            --image gcr.io/$PROJECT_ID/$SERVICE \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated \
            --quiet
