name: Deploy to Cloud Run

on:
  push:
    branches: [main]

env:
  PROJECT_ID: huashui-ai-450006
  REGION: asia-east1
  SERVICE: image-processor

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: 'Configure Docker'
        run: gcloud auth configure-docker

      - name: 'Build and Deploy'
        run: |
          # 使用 --no-source 選項來避免日誌問題
          gcloud builds submit --tag gcr.io/$PROJECT_ID/$SERVICE \
            --timeout=1800s \
            --no-source \
            || true  # 即使日誌出錯也繼續執行

          # 等待一下確保映像已經構建完成
          sleep 30

          # 部署到 Cloud Run
          gcloud run deploy $SERVICE \
            --image gcr.io/$PROJECT_ID/$SERVICE \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated
