name: Deploy to Cloud Run

on:
  push:
    branches: [main]

env:
  PROJECT_ID: huashui-ai-450006
  REGION: asia-east1
  SERVICE: image-processor

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: 'Configure Docker'
        run: gcloud auth configure-docker

      - name: 'Build and Deploy'
        run: |
          # Build the Docker image
          docker build -t gcr.io/$PROJECT_ID/$SERVICE .
          # Push to Container Registry
          docker push gcr.io/$PROJECT_ID/$SERVICE

          # Deploy to Cloud Run
          gcloud run deploy $SERVICE \
            --image gcr.io/$PROJECT_ID/$SERVICE \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated \
            --set-env-vars="GOOGLE_CLOUD_BUCKET_NAME=${{ secrets.GOOGLE_CLOUD_BUCKET_NAME }}"
